#spring:
#  datasource:
#    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#h2:
#  console:
#    enabled: true
#    path: /console
#    settings:
#      trace: false
#      web-allow-others: false

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public

  datasource:
    url: jdbc:postgresql://${bcn_adm_db_host:localhost}:${bcn_adm_db_port:5432}/bcn_adm
    username: root
    password: root
    driverClassName: org.postgresql.Driver